#GIVEN AN ARRAY OF INTERGER SLOPES, FIND THE MINIMIMUM INCREMENT/DECREMENT NEEDED TO MAKE THE ARRAY INCREASING OR DECREASING
#9,7,8,6,2,3,3 -> 2
#1,2,2,3,3,4 ->0 (ALREADY INCREASING

def minChange(slopes):
