service: packerize

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  region: 'us-east-2'
  profile: personal

  versionFunctions: false
  logRetentionInDays: 30

functions:
  slack:
    handler: slack.handler
    memorySize: 512
    timeout: 30
    events:
      - cloudwatchEvent:
          name: 'CodeBuildToLambda'
          event:
            source:
              - "aws.codebuild"
            detail-type:
              - "CodeBuild Status Report"
            detail:
              project-name:
                - 'Packerize_build'
              build-status:
                - 'IN_PROGRESS'
                - 'SUCCEEDED'
                - 'FAILED'
                - 'STOPPED'